### ISSUE TITLE
ollama-js client library implementieren

### ISSUE THREAD

**Issue by jorditost** [fidelthomet/futuring-machines#4]
https://github.com/ollama/ollama-js

**Comment by fidelthomet** [comment]
I see they've added browser support now. Still, I don't see any immediate benefits from switching as there's no big difference compared to using the API directly.

But feel free to reopen if you think it will become useful :)

**Comment by jorditost** [comment]
We started facing some problems with the LLM responses since we changed to our workstation (with GPU). It seems that the response arrives too fast (!) and because of this, the client has problems problems parsing it. We fixed it already to some extent, but it still happens from time to time (especially when getting JSON responses). Our guess was that the ollama-js client might already deal with this issue.

**Comment by jorditost** [comment]
I reopened this issue since we are still having following problems (see below). One guess is that the Ollama library could be already managing such problems with the responses.

**White bubbles**
<img width="1440" alt="Bildschirmfoto_2024-06-05_um_14 27 52" src="https://github.com/fidelthomet/futuring-machines/assets/859148/688555c7-f462-4652-a7b1-82e78e2c0a9d">

**"Broken answers"**
See console error.
![image](https://github.com/fidelthomet/futuring-machines/assets/859148/ead6e397-2400-4f84-8147-94c4e4c310dc)

**Comment by fidelthomet** [comment]
switching to the library here wouldn't help as the problem lies in the answer of the LLM, i.e. not returning the response in the desired format. the client side errors come from parsing the mangled response.

Broken answers (the response is not valid json): This error is caught now offering the options to try again or cancel

White Bubbles (the response is valid json, but not in the expected format): This is more tricky to handle. It would be good to see the server response. If this issue is reoccurring please open a new issue for that
